"""empty message

Revision ID: 0f8cd1874fb3
Revises: bce6efc3aab1
Create Date: 2020-05-22 19:33:09.934989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f8cd1874fb3'
down_revision = 'bce6efc3aab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_file',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('mission_url', sa.String(length=128), nullable=True),
    sa.Column('mission_name', sa.String(length=64), nullable=True),
    sa.Column('file_url', sa.String(length=128), nullable=True),
    sa.Column('file_name', sa.String(length=64), nullable=True),
    sa.Column('student_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['tb_student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('tb_student', 'mission_url')
    op.drop_column('tb_student', 'file_url')
    op.drop_column('tb_student', 'file_name')
    op.drop_column('tb_student', 'mission_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_student', sa.Column('mission_name', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('tb_student', sa.Column('file_name', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('tb_student', sa.Column('file_url', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('tb_student', sa.Column('mission_url', mysql.VARCHAR(length=128), nullable=True))
    op.drop_table('tb_file')
    # ### end Alembic commands ###
