"""empty message

Revision ID: 137c1343020a
Revises: 54d82fa8fead
Create Date: 2020-04-08 20:49:59.427033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '137c1343020a'
down_revision = '54d82fa8fead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_teacher', sa.Column('sign_finished', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_teacher', 'sign_finished')
    # ### end Alembic commands ###
