"""empty message

Revision ID: 335f93a9934d
Revises: 
Create Date: 2020-02-16 17:34:03.552540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '335f93a9934d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=5), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('hash_password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_user')
    # ### end Alembic commands ###
