"""empty message

Revision ID: 3e68d99e73bf
Revises: 335f93a9934d
Create Date: 2020-02-16 22:05:04.217986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e68d99e73bf'
down_revision = '335f93a9934d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_student',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=5), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('hash_password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tb_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_user',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('hash_password', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='gb2312',
    mysql_engine='InnoDB'
    )
    op.drop_table('tb_student')
    # ### end Alembic commands ###
