"""empty message

Revision ID: 5b2c7cca05e4
Revises: d6ac26e99470
Create Date: 2020-04-01 15:27:49.711793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b2c7cca05e4'
down_revision = 'd6ac26e99470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_student', sa.Column('file_name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_student', 'file_name')
    # ### end Alembic commands ###
