"""empty message

Revision ID: abe43c0ac337
Revises: 
Create Date: 2020-02-11 19:55:45.322007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abe43c0ac337'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=5), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('hash_password', sa.String(length=128), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['tb_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_user_email'), 'tb_user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_user_email'), table_name='tb_user')
    op.drop_table('tb_user')
    # ### end Alembic commands ###
