"""empty message

Revision ID: b5a506628982
Revises: f543cbd388b4
Create Date: 2020-02-14 13:26:01.364272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a506628982'
down_revision = 'f543cbd388b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tb_user_phone', table_name='tb_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tb_user_phone', 'tb_user', ['phone'], unique=True)
    # ### end Alembic commands ###
