"""empty message

Revision ID: b88b1dd95d2f
Revises: 1dc0f2b335ff
Create Date: 2020-04-29 13:01:35.809955

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b88b1dd95d2f'
down_revision = '1dc0f2b335ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_sign',
    sa.Column('sign_time', sa.String(length=32), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['tb_student.id'], ),
    sa.PrimaryKeyConstraint('sign_time')
    )
    op.drop_column('tb_student', 'sign_times')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_student', sa.Column('sign_times', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
    op.drop_table('tb_sign')
    # ### end Alembic commands ###
