"""empty message

Revision ID: bab9ba2c8837
Revises: ffc126974058
Create Date: 2020-03-06 20:09:51.726694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab9ba2c8837'
down_revision = 'ffc126974058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_teacher', sa.Column('contain', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_teacher', 'contain')
    # ### end Alembic commands ###
