"""empty message

Revision ID: bce6efc3aab1
Revises: 99b14316b37a
Create Date: 2020-05-20 20:17:00.466516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bce6efc3aab1'
down_revision = '99b14316b37a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_student', sa.Column('mission_name', sa.String(length=64), nullable=True))
    op.add_column('tb_student', sa.Column('mission_url', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_student', 'mission_url')
    op.drop_column('tb_student', 'mission_name')
    # ### end Alembic commands ###
