"""empty message

Revision ID: c5fd5bf1a9dd
Revises: c851f7831e7d
Create Date: 2020-04-30 10:13:26.825931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5fd5bf1a9dd'
down_revision = 'c851f7831e7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_teacher', sa.Column('is_open_sign', sa.Integer(), nullable=True,default=0))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_teacher', 'is_open_sign')
    # ### end Alembic commands ###
