"""empty message

Revision ID: c851f7831e7d
Revises: b88b1dd95d2f
Create Date: 2020-04-29 21:03:38.864257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c851f7831e7d'
down_revision = 'b88b1dd95d2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_student', sa.Column('personal_theme', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_student', 'personal_theme')
    # ### end Alembic commands ###
