"""empty message

Revision ID: cddad580d020
Revises: dcbee262e3ee
Create Date: 2020-05-22 20:55:22.535863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cddad580d020'
down_revision = 'dcbee262e3ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_file',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('mission_url', sa.String(length=128), nullable=True),
    sa.Column('mission_name', sa.String(length=64), nullable=True),
    sa.Column('file_url', sa.String(length=128), nullable=True),
    sa.Column('file_name', sa.String(length=64), nullable=True),
    sa.Column('student_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['tb_student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_file')
    # ### end Alembic commands ###
