"""empty message

Revision ID: d6ac26e99470
Revises: eafd549ca4a0
Create Date: 2020-04-01 10:28:15.470557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6ac26e99470'
down_revision = 'eafd549ca4a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_student', sa.Column('file_url', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_student', 'file_url')
    # ### end Alembic commands ###
