"""empty message

Revision ID: dcbee262e3ee
Revises: 0f8cd1874fb3
Create Date: 2020-05-22 20:54:50.302175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dcbee262e3ee'
down_revision = '0f8cd1874fb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_file',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('mission_url', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('mission_name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('file_url', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('file_name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('student_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['tb_student.id'], name='tb_file_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='gb2312',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
