"""'2'

Revision ID: eafd549ca4a0
Revises: d3b3333107ad
Create Date: 2020-03-25 11:25:36.902929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eafd549ca4a0'
down_revision = 'd3b3333107ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_inform', sa.Column('title', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_inform', 'title')
    # ### end Alembic commands ###
