"""empty message

Revision ID: f543cbd388b4
Revises: abe43c0ac337
Create Date: 2020-02-13 18:59:34.951664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql                     # 
#  数据库迁移的相关记录都在各个版本中
# revision identifiers, used by Alembic.
revision = 'f543cbd388b4'
down_revision = 'abe43c0ac337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_user', sa.Column('phone', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_tb_user_phone'), 'tb_user', ['phone'], unique=True)
    op.drop_index('ix_tb_user_email', table_name='tb_user')
    op.drop_column('tb_user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_user', sa.Column('email', mysql.VARCHAR(length=64), nullable=True))
    op.create_index('ix_tb_user_email', 'tb_user', ['email'], unique=True)
    op.drop_index(op.f('ix_tb_user_phone'), table_name='tb_user')
    op.drop_column('tb_user', 'phone')
    # ### end Alembic commands ###
