"""empty message

Revision ID: ffc126974058
Revises: 950d611eee19
Create Date: 2020-03-03 19:58:05.310546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffc126974058'
down_revision = '950d611eee19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_student', sa.Column('teacher_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'tb_student', 'tb_teacher', ['teacher_id'], ['id'])
    op.add_column('tb_teacher', sa.Column('introduction', sa.Text(length=1000), nullable=True))
    op.add_column('tb_teacher', sa.Column('theme', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_teacher', 'theme')
    op.drop_column('tb_teacher', 'introduction')
    op.drop_constraint(None, 'tb_student', type_='foreignkey')
    op.drop_column('tb_student', 'teacher_id')
    # ### end Alembic commands ###
